// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-mobile/Current.tsx": () => import("../components/mockups/hero-mobile/Current.tsx"),
  "./components/mockups/hero-mobile/FieldGrid.tsx": () => import("../components/mockups/hero-mobile/FieldGrid.tsx"),
  "./components/mockups/hero-mobile/Ledger.tsx": () => import("../components/mockups/hero-mobile/Ledger.tsx"),
  "./components/mockups/hero-mobile/TypeIndex.tsx": () => import("../components/mockups/hero-mobile/TypeIndex.tsx"),
  "./components/mockups/hero-cta/Current.tsx": () => import("../components/mockups/hero-cta/Current.tsx"),
  "./components/mockups/hero-cta/Grounded.tsx": () => import("../components/mockups/hero-cta/Grounded.tsx"),
  "./components/mockups/hero-cta/Ivory.tsx": () => import("../components/mockups/hero-cta/Ivory.tsx"),
  "./components/mockups/hero-cta/QuietMetal.tsx": () => import("../components/mockups/hero-cta/QuietMetal.tsx")
};
